### ISSUE TITLE
Getting `noVNC encountered an error` after update

### ISSUE THREAD

**Issue by rgronberg** [realies/soulseek-docker#43]
Running you docker in unRAID, been working great. Just upgraded my soulseek container to the latest and am now seeing an issue where noVNC does not load.

```
TypeError: WebUtil.initLogging is not a function
    at Object.updateLogging (http://sam.local:6080/app/ui.js:1656:17)
    at Object.initSettings (http://sam.local:6080/app/ui.js:151:12)
    at Object.start (http://sam.local:6080/app/ui.js:59:12)
    at http://sam.local:6080/app/ui.js:47:27
```
<img width="514" alt="Screen Shot 2022-03-15 at 15 47 52" src="https://user-images.githubusercontent.com/15242023/158484906-7bea0bf4-b0e9-4fd8-a410-80f00385b1c6.png">

The container logs look ok:
```
2022-03-15 15:43:06,922 INFO Set uid to user 0 succeeded
2022-03-15 15:43:06,926 INFO supervisord started with pid 14
2022-03-15 15:43:07,930 INFO spawned: 'tigervnc' with pid 16
2022-03-15 15:43:07,932 INFO spawned: 'openbox' with pid 17
2022-03-15 15:43:07,935 INFO spawned: 'novnc' with pid 18
2022-03-15 15:43:07,936 INFO spawned: 'soulseek' with pid 19
2022-03-15 15:43:09,114 INFO success: tigervnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-15 15:43:09,114 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-15 15:43:09,114 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-15 15:43:09,114 INFO success: soulseek entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by rgronberg** [comment]
This is a browser specific issue
